spring.application.name=-Language-Translator-Web-App-Java-NLP-Library-
app.dictionary.path.en=classpath:translation_data_en.txt

# --- Configurarea Dinamic? a Modelelor NLP ---
# ACUM SE INCARCA DOAR MODELELE 'en'
nlp.token={en: classpath:token/en-token.bin}
nlp.pos={en: classpath:pos/en-pos.bin}
nlp.models.lemmatizer={en: classpath:models/en-lemmatizer.dict}