spring.application.name=-Language-Translator-Web-App-Java-NLP-Library-
app.dictionary.path.en=classpath:translation_data_en.txt

nlp.models.token.en=classpath:token/en-token.bin
nlp.models.token.de=classpath:token/de-token.bin

nlp.models.pos.en=classpath:pos/en-pos.bin
nlp.models.pos.de=classpath:pos/de-pos.bin

nlp.models.lemmatizer.en=classpath:models/en-lemmatize.dict
nlp.models.lemmatizer.de=classpath:models/de-lemmatize.dict