spring.application.name=-Language-Translator-Web-App-Java-NLP-Library-

# Dic?ionarele
app.dictionary.paths={'en':'classpath:translation_data_en.txt', 'de':'classpath:translation_data_de.txt'}

# COREC?IE: S-au ad?ugat ghilimele simple în interiorul Map-urilor pentru SpEL
nlp.token={'en':'classpath:token/en-token.bin', 'de':'classpath:token/de-token.bin'}
nlp.pos={'en':'classpath:pos/en-pos.bin', 'de':'classpath:pos/de-pos.bin'}
nlp.models.lemmatizer={'en':'classpath:models/en-lemmatizer.dict', 'de':'classpath:models/de-lemmatizer.dict'}